Add iNaturalist class & import method
zooniverse/panoptes-python-client pull request #289
Opened 2022-11-04 21:09 UTC by zwolf

Adds a simple iNaturalist object that has a single method. That method sends a POST request to Panoptes that starts an iNat Observation import. It uses the base `Panoptes.client()` POST method, which includes authentication. 

I've included two tests which are currently failing--I can't figure out why the mock isn't working. The SubjectSet test was the model and it sure seems to me that they that method should be stubbed and not actually trying to call out. It's a simple enough test that it might be easier to just remove it, but let me know if I'm missing something obvious.

2022-11-07 15:57 UTC, yuenmichelle1 requested changes
This looks fine to me. Just a couple small changes

- I think we should also include Inaturalist import in __init__.py
- Not a blocker, but should we include this within user_guide or panoptes_client.rst?

2022-11-07 17:56 UTC, yuenmichelle1 commented
Yup this looks good. 👍  I think it belongs. So that we can run `from panoptes_client import Inaturalist` in a direct manner.

2022-11-10 21:11 UTC, zwolf commented on panoptes_client/__init__.py
> +from panoptes_client.inaturalist import Inaturalist
Required for convenient importing

2022-11-10 22:16 UTC, yuenmichelle1 approved these changes
lgtm

2022-11-30 18:32 UTC, merged