implement fetch_settings to project_preferences class
zooniverse/panoptes-python-client pull request #306
Opened 2024-02-21 19:31 UTC by Tooyosi

implement fetch_settings to project_preferences class

2024-02-22 16:02 UTC, lcjohnso requested changes
Please add a docstring for documentation.  Also consider adding usage example for the ReadTheDocs site (https://panoptes-python-client.readthedocs.io/) -- especially if there is already example usage of setting the `settings.workflow_id` parameter.

2024-02-23 18:13 UTC, yuenmichelle1 requested changes
Hey Toyosi!

I had a couple of changes requested. But I think we should revisit the merged PR: https://github.com/zooniverse/panoptes/pull/4280

Readability wise, I found it confusing that your method is called `fetch_settings` but I'm receiving more than just the settings of the UPP. (I'm receiving the whole UPP). I found a similar issue in the corresponding Panoptes PR as well. 

There is a way for us to only include attributes we want with our serializers in panoptes. 
See: https://github.com/zooniverse/restpack_serializer/tree/panoptes-api-version?tab=readme-ov-file#serialization

I think let's pair next week re-working the Panoptes PR to either change naming of methods or to update the methods so that it is returning what the method name says it will return.

2024-02-23 18:13 UTC, yuenmichelle1 commented on panoptes_client/project_preferences.py
> +        if _project_id is not None:
This check for _project_id feels redundant since you have a check that raises TypeError that sets the project id.

2024-02-29 16:57 UTC, yuenmichelle1 approved these changes
Awesome code changes here alongside the changes on https://github.com/zooniverse/panoptes/pull/4299  look good. 👍  

Not blocking, but post our convo with Cliff this morning, I think it is well worth adding documentation to our user guide as well. Within "Other examples" section. See: https://panoptes-python-client.readthedocs.io/en/latest/user_guide.html#other-examples

Additions to user guide doc can be added here: https://github.com/zooniverse/panoptes-python-client/blob/master/docs/user_guide.rst#other-examples

2024-02-29 17:17 UTC, lcjohnso commented
^^ I agree with above: please add usage example to User Guide doc pages -- both for your new `fetch_settings()` function and the existing `save_settings()` function. Ping me for a re-review when you have docs for me to look at.

2024-03-01 17:30 UTC, lcjohnso approved these changes
@Tooyosi I made small edits to the user guide docs text; it is good to go now -- thanks!

2024-03-03 14:58 UTC, merged